export const BASE_PREMISE_GENERATION_DEVELOPER_PROMPT = `You are generating observational material.
Return valid JSON only in exactly this shape:

{
  "items": [
    { "world": "unspecified", "premise": "one sentence collision note" }
  ]
}
`;

/**
 * OVERLAP COMEDY ENGINE — Phase 1 (Discovery / Raw Material)
 *
 * IMPORTANT:
 * Phase 1 produces ONLY raw single-sentence overlap statements.
 * These statements should already be:
 * - concrete
 * - maximized escalation (top-rung)
 * - declarative certainty (no hedging)
 *
 * Output is strict JSON with 3 arrays: items, outerField, compression.
 */
export const OVERLAP_PHASE1_DEVELOPER_PROMPT_MINIMAL = `You are generating observational raw material for John Branyan's Overlap Comedy Engine (Phase 1).

GOAL
Surface diverse, rewriteable, single-sentence OVERLAP statements derived from the premise’s ASSOCIATION FIELDS.
An overlap occurs when two idea-domains are forced to share one rule set (misapplied standard, wrong stakes, wrong timeline, wrong evaluation criteria, wrong purpose).

These are NOT jokes.
Do not write punchlines. Do not "be funny." Do not use joke templates.

CERTAINTY (NON-NEGOTIABLE)
- No hedging language: "feels like," "looks like," "seems," "might," "probably," "kind of," "sort of," "almost," "basically," "I imagine," "I picture."

CORE METHOD (SILENT — DO NOT OUTPUT)
1) Extract 3–6 ANCHORS from the premise.
   - Include implied anchors like: audience, setting, transaction, status, marketing language, social behavior.
2) For EACH anchor, build a small ASSOCIATION FIELD (8–15 items).
   - Include concrete: objects, roles, places, processes, rituals, standards, slang, adjacent industries.
3) Create overlaps ONLY by pairing TWO items from DIFFERENT association fields.
   - Each overlap must contain evidence of BOTH fields.
   - If the sentence could exist without the premise context, discard it.
4) Write each overlap as ONE maximized, declarative sentence.

ANCHOR-FIELD REQUIREMENT (THE RULE THAT MATTERS)
- Each overlap statement must combine at least TWO different association fields from the premise.
- If a sentence is essentially “one noun used as a random substitute,” discard it and regenerate using cross-field pairing.

NO RANDOM SUBSTITUTE ABSURDITY (NON-NEGOTIABLE)
- Do NOT generate novelty substitutions like "using hay as X" (confetti, vinyl records, computers, smoothies, insulation, clothing, etc.).
- If you drift into that pattern, stop and rewrite: use two association fields instead (e.g., marketing language + commodity, certification + barn supply, status + bulk pricing, etc.).

ITEM RULES (NON-NEGOTIABLE)
- EXACTLY one sentence per item.
- Each item expresses ONE overlap angle.
- Each item contains at least one concrete object or action.
- Avoid thesis framing, listicles, and "balanced comparison" scaffolds.
- Avoid invented agency/actions not implied by the premise.
- Vary sentence shapes across the set.

BATCH REQUIREMENTS
- items: 12–18 CORE overlaps tightly tied to cross-field pairings from the premise anchors.
- outerField: 12–25 topic-adjacent overlaps produced by taking ONE hop outward from any strong association, then pairing across fields again.
- compression: 5–10 distilled one-sentence lines based on the strongest CORE overlaps (still certain, still concrete, still maximized).

OUTPUT FORMAT (STRICT)
Return valid JSON only in exactly this shape:

{
  "items": [
    { "world": "unspecified", "premise": "one sentence overlap statement" }
  ],
  "outerField": [
    { "world": "unspecified", "premise": "one sentence topic-adjacent overlap statement" }
  ],
  "compression": [
    { "world": "unspecified", "premise": "one sentence distilled line" }
  ]
}
`;


// Backward compatibility alias
export const BASE_GENERATION_DEVELOPER_PROMPT_FINAL = BASE_PREMISE_GENERATION_DEVELOPER_PROMPT;

/**
 * OVERLAP COMEDY ENGINE — Phase 2 (Re-author + Report Layout)
 *
 * Phase 2 does NOT discover overlaps.
 * It reauthors the Phase 1 overlap statements using a selected StyleContract,
 * then arranges them into the report layout.
 */
export const OVERLAP_PHASE2_REAUTHOR_AND_LAYOUT_PROMPT_MINIMAL = `You are re-authoring observational material (Phase 2) for John Branyan's Overlap Comedy Engine.

The input is raw material generated by Phase 1.
Each input premise is a single-sentence overlap statement (wrong rule set / misapplied standard).

Your task:
1) Re-author each statement in the specified voice/style contract.
2) Arrange the re-authored statements into a report layout.

IMPORTANT GUIDELINES (NON-NEGOTIABLE)
– Preserve the underlying overlap of each statement.
– Keep concrete anchors identifiable; do not generalize away specifics.
– Do not introduce new overlap ideas; re-author only.
– Maintain CERTAINTY: eliminate hedging language ("feels like," "looks like," "seems," "might," "probably," "while," "in a world," etc.).
– Do not write jokes/punchlines or joke templates.

STYLE CONTRACT INTERPRETER (NON-NEGOTIABLE)
You will receive a StyleContract object with fields:
- voiceDescription, diction, rhythm, energy
- languageConstraints (array of binding rules)
- structuralBehavior (multiLine, tagging)
Treat these as requirements:
- Apply voiceDescription as the narrator posture.
- Apply diction as word-choice bias.
- Apply rhythm as sentence shape guidance.
- Apply energy as intensity level (do not drift).
- Obey every languageConstraints item as a hard rule.
- structuralBehavior.multiLine: if discouraged, keep blocks short; if forbidden, keep single-line.

CHAT-LIKE SILENT REVISION (DO NOT PRINT)
Before outputting, silently revise:
1) Certainty check: remove hedge language and write declaratives.
2) Concrete check: remove generic MBA phrasing; keep objects/actions on the page.
3) Variety check: avoid repeating the same sentence stem repeatedly.

REPORT LAYOUT (PLAIN TEXT)
Title: John Branyan's Overlap Comedy Engine — Overlap Analysis Report

Premise Clarified: <one tightened sentence that restates the user's premise; do NOT invent a new premise or add "unconventional scenarios">

Surface Assumptions:
- EXACTLY 6–10 bullets.
- Behavioral assumptions only (what people assume/expect/pretend/act like), not factual claims about regulations/health/racing.
- No invented expertise or industry facts.

Core Overlaps:
OVERLAP #1
<reauthored sentence>
...
OVERLAP #N
<reauthored sentence>

Outer Field Overlaps:
- <reauthored sentence>
...

Compression Lines:
- <reauthored sentence>
...

OUTPUT FORMAT (STRICT)
Return valid JSON only in exactly this shape:

{
  "report": "<full report as plain text with line breaks>"
}

Return the same number of re-authored sentences as inputs in each section, preserving order.
`;

// Backward compatibility / legacy prompt
export const REWRITE_DEVELOPER_PROMPT_SNAPSHOT_ESCALATION_FINAL = OVERLAP_PHASE2_REAUTHOR_AND_LAYOUT_PROMPT_MINIMAL;

